services:
  postgres:
    container_name: postgres-sql-shopping-cart
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: shopping_cart
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-shopping-cart
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-shopping-cart
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-shopping-cart:
    driver: bridge
volumes:
  postgres:
    driver: local
